"""
generate_report.py
===================
Assembles all pipeline outputs into a single Markdown validation report,
structured the way a model document for internal regulatory review would
be structured: intended use, data provenance, performance, subgroup and
calibration evidence, interpretability, uncertainty, and known limitations.

This is deliberately a template you should edit by hand once real PTB-XL
results are in -- the point of auto-generating it is to make sure you
never forget a required section, not to skip writing the prose yourself.
"""

import json
import os
from datetime import datetime


def _read_json(path):
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return None


def generate_report(out_dir="outputs"):
    metrics = _read_json(os.path.join(out_dir, "metrics_summary.json")) or {}
    survival = _read_json(os.path.join(out_dir, "survival_results.json")) or {}
    uncertainty = _read_json(os.path.join(out_dir, "uncertainty_results.json")) or {}

    subgroup_csv = os.path.join(out_dir, "subgroup_report.csv")
    subgroup_table = ""
    if os.path.exists(subgroup_csv):
        import pandas as pd
        df = pd.read_csv(subgroup_csv)
        subgroup_table = df.to_markdown(index=False)

    report = f"""# Model Validation Report — ECG Arrhythmia Classifier

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Status:** DRAFT — auto-generated scaffold, requires clinical/statistical review before use

---

## 1. Intended Use

This model classifies short-duration 12-lead ECG recordings into one of
several arrhythmia-related diagnostic superclasses, intended as a
**decision-support aid** for triage or pre-screening — not a standalone
diagnostic device. Any clinical use would require prospective validation
and is out of scope for this offline analysis.

> ⚠️ **Note on data provenance:** {"This run used the real PTB-XL dataset." if False else
    "This run used SYNTHETIC data generated by `data_loader.py` for pipeline "
    "development and testing. Before this report can support any real claim, "
    "re-run `run_pipeline.py --real_data` against the downloaded PTB-XL dataset "
    "(https://physionet.org/content/ptb-xl/) and regenerate this report."}

## 2. Data

- **Source:** PTB-XL (or synthetic stand-in — see note above), 12-lead ECG,
  patient-level demographic metadata (age, sex).
- **Split strategy:** Patient-level train/val/test split (`GroupShuffleSplit`
  on `patient_id`) to prevent patient leakage across splits.
- **Test set size:** {metrics.get("n_test", "N/A")} recordings.

## 3. Model

1D-CNN + BiLSTM temporal classifier (`src/model.py`). Convolutional layers
extract local morphological features (QRS/P/T-wave shape); the BiLSTM
captures longer-range rhythm irregularities. See `model.py` docstring for
the full architecture rationale and Transformer swap-in notes.

## 4. Offline Performance

| Metric | Mean | 95% CI (bootstrap, n=1000) |
|---|---|---|
| Accuracy | {metrics.get("accuracy", {}).get("mean", "N/A")} | {metrics.get("accuracy", {}).get("ci_95", "N/A")} |
| Macro AUC (OvR) | {metrics.get("macro_auc_ovr", {}).get("mean", "N/A")} | {metrics.get("macro_auc_ovr", {}).get("ci_95", "N/A")} |

Confidence intervals estimated via bootstrap resampling of the test set
(see `evaluate.py::bootstrap_ci`).

## 5. Subgroup / Fairness Analysis

Maximum accuracy gap across evaluated subgroups: **{metrics.get("max_subgroup_accuracy_gap", "N/A")}**

{subgroup_table if subgroup_table else "_No subgroup report found — run evaluate.py first._"}

**Interpretation guidance:** any subgroup gap above a pre-specified
threshold (e.g., 0.05 accuracy) should be investigated before deployment —
check training data representation for that subgroup first, then consider
subgroup-specific calibration or reweighting.

## 6. Calibration

See `calibration_curve.png`. A well-calibrated model's curve should track
the diagonal — points above the diagonal indicate underconfidence, points
below indicate overconfidence in that probability range.

## 7. Interpretability

Per-sample SHAP attributions are in `shap_explanations.png`, overlaid
directly on the ECG waveform so a clinical reviewer can see *where* in
the beat the model's decision is concentrated (e.g., QRS complex vs.
T-wave region).

## 8. Uncertainty Quantification

MC Dropout predictive entropy (30 stochastic forward passes):

- Mean entropy on **correct** predictions: {uncertainty.get("mean_entropy_correct", "N/A")}
- Mean entropy on **incorrect** predictions: {uncertainty.get("mean_entropy_incorrect", "N/A")}

If incorrect predictions show meaningfully higher entropy than correct
ones, the uncertainty signal is informative and could gate low-confidence
predictions for human review. See `uncertainty_histogram.png`.

## 9. Survival / Prognostic Value (exploratory)

> ⚠️ Outcomes in this analysis are **simulated** — see `survival_analysis.py`
> docstring. Methodology is real; substitute real longitudinal outcomes
> before drawing clinical conclusions.

- Log-rank test across predicted classes: statistic = {survival.get("logrank_test_statistic", "N/A")}, p = {survival.get("logrank_p_value", "N/A")}
- Cox model concordance index (age + sex + predicted class): {survival.get("cox_concordance_index", "N/A")}

See `km_curves_by_class.png` and `cox_model_summary.csv` for full hazard
ratios and confidence intervals per predicted class.

## 10. Known Limitations

- Trained/evaluated on {"synthetic" if True else "real"} data in this run — **not** a
  substitute for real PTB-XL (or institution-specific) validation.
- Single-label diagnostic superclass simplification; real clinical
  presentations are frequently multi-label.
- Survival outcomes are simulated, not real longitudinal follow-up.
- No external/held-out-site validation performed (single-dataset only).
- Model has not undergone prospective or clinician-in-the-loop evaluation.

## 11. Next Steps for Submission-Readiness

1. Re-run against real PTB-XL (or target institution's data).
2. Expand subgroup analysis to device cohort / lead configuration if applicable.
3. Add external validation on a second, independent dataset.
4. Replace simulated survival outcomes with real registry-linked outcomes.
5. Clinical review of SHAP explanations by a cardiologist for face validity.
6. Formal risk documentation per design-control process.

---
*Auto-generated by `src/generate_report.py`. Edit directly once reviewed.*
"""

    out_path = os.path.join(out_dir, "VALIDATION_REPORT.md")
    with open(out_path, "w") as f:
        f.write(report)
    print(f"Wrote {out_path}")
    return out_path


if __name__ == "__main__":
    out_dir = "../outputs" if os.path.basename(os.getcwd()) == "src" else "outputs"
    generate_report(out_dir=out_dir)
